name: Update Production Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Connect to production server and run batch script
              uses: appleboy/ssh-action@master
              with:
                    host: ${{ secrets.BRADON_SERVER_IP }}
                    username: ${{ secrets.BRADON_SERVER_USERNAME }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    script: |
                        cd C:\Users\blbarfuss\Desktop\batchfile.bat
